@hostname = http://localhost:4000

GET {{hostname}}

###

POST {{hostname}}/register
Content-Type: application/json

{
    "name": "clench",
    "email": "clench@gmail.com",
    "password": "secret"
}

###

POST {{hostname}}/login
Content-Type: application/json

{
    "email": "clench@gmail.com",
    "password": "secret"
}

###

 